
<!doctype html><html lang="nl-NL"><head><meta charset="UTF-8"><meta http-equiv="x-ua-compatible" content="ie=edge"><title>
W E B D E V E L O P E R ™
</title><meta name="viewport" content="width=device-width, initial-scale=1">@include('layout.favicon');<meta name="description" content="Hi I&#039;m Hieu and Hieutube is my personal website. I&#039;m a web developer from The Netherlands." /><meta name="robots" content="index, follow" /><meta name="googlebot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" /><meta name="bingbot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" /><link rel="canonical" href="https://hieutube.com/" /><meta property="og:locale" content="en_US" /><meta property="og:type" content="website" /><meta property="og:title" content="W E B D E V E L O P E R ™" /><meta property="og:description" content="Hi I&#039;m Hieu and Hieutube is my personal website. I&#039;m a web developer from The Netherlands." /><meta property="og:url" content="https://hieutube.com/" /><meta property="og:site_name" content="Hieutube" /><meta property="article:modified_time" content="2020-05-20T20:21:14+00:00" /><meta name="twitter:card" content="summary_large_image" /> <script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":["Person","Organization"],"@id":"https://hieutube.com/#/schema/person/48f0bca4915cbbc49856478d4020c3c3","name":"admin","image":{"@type":"ImageObject","@id":"https://hieutube.com/#personlogo","inLanguage":"en-US","url":"https://secure.gravatar.com/avatar/58bc5d5e4353cb4e300be313543e4d03?s=96&d=mm&r=g","caption":"admin"},"logo":{"@id":"https://hieutube.com/#personlogo"}},{"@type":"WebSite","@id":"https://hieutube.com/#website","url":"https://hieutube.com/","name":"Hieutube","description":"","publisher":{"@id":"https://hieutube.com/#/schema/person/48f0bca4915cbbc49856478d4020c3c3"},"potentialAction":[{"@type":"SearchAction","target":"https://hieutube.com/?s={search_term_string}","query-input":"required name=search_term_string"}],"inLanguage":"en-US"},{"@type":"WebPage","@id":"https://hieutube.com/#webpage","url":"https://hieutube.com/","name":"W E B D E V E L O P E R \u2122","isPartOf":{"@id":"https://hieutube.com/#website"},"about":{"@id":"https://hieutube.com/#/schema/person/48f0bca4915cbbc49856478d4020c3c3"},"datePublished":"2019-06-30T20:23:38+00:00","dateModified":"2020-05-20T20:21:14+00:00","description":"Hi I'm Hieu and Hieutube is my personal website. I'm a web developer from The Netherlands.","inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://hieutube.com/"]}]}]}</script> <link rel='dns-prefetch' href='//fonts.googleapis.com' /><link rel='dns-prefetch' href='//s.w.org' /> <script type="text/javascript">window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/12.0.0-1\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/12.0.0-1\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/hieutube.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.4.1"}};
	/*! This file is auto-generated */
	!function(e,a,t){var r,n,o,i,p=a.createElement("canvas"),s=p.getContext&&p.getContext("2d");function c(e,t){var a=String.fromCharCode;s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,e),0,0);var r=p.toDataURL();return s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,t),0,0),r===p.toDataURL()}function l(e){if(!s||!s.fillText)return!1;switch(s.textBaseline="top",s.font="600 32px Arial",e){case"flag":return!c([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])&&(!c([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!c([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]));case"emoji":return!c([55357,56424,55356,57342,8205,55358,56605,8205,55357,56424,55356,57340],[55357,56424,55356,57342,8203,55358,56605,8203,55357,56424,55356,57340])}return!1}function d(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(i=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},o=0;o<i.length;o++)t.supports[i[o]]=l(i[o]),t.supports.everything=t.supports.everything&&t.supports[i[o]],"flag"!==i[o]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[i[o]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(r=t.source||{}).concatemoji?d(r.concatemoji):r.wpemoji&&r.twemoji&&(d(r.twemoji),d(r.wpemoji)))}(window,document,window._wpemojiSettings);</script> <style type="text/css">img.wp-smiley,
img.emoji {
display: inline !important;
border: none !important;
box-shadow: none !important;
height: 1em !important;
width: 1em !important;
margin: 0 .07em !important;
vertical-align: -0.1em !important;
background: none !important;
padding: 0 !important;
}</style><link rel='stylesheet' id='wp-block-library-css'  href='https://hieutube.com/wp-includes/css/dist/block-library/style.min.css?ver=5.4.1' type='text/css' media='all' /><link rel='stylesheet' id='hieutube-fonts-css'  href='https://fonts.googleapis.com/css?family=Open+Sans%3A300%2C400%2C700%2C800&#038;ver=1.0.0' type='text/css' media='screen' /><link rel='stylesheet' id='hieutube-styles-css'  href='https://hieutube.com/wp-content/themes/hieutube/dist/app.80980946000d99b7c908.css?ver=1.0.0' type='text/css' media='screen' /><link rel='https://api.w.org/' href='https://hieutube.com/wp-json/' /><link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://hieutube.com/xmlrpc.php?rsd" /><link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://hieutube.com/wp-includes/wlwmanifest.xml" /><meta name="generator" content="WordPress 5.4.1" /><link rel='shortlink' href='https://hieutube.com/' /><link rel="alternate" type="application/json+oembed" href="https://hieutube.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fhieutube.com%2F" /><link rel="alternate" type="text/xml+oembed" href="https://hieutube.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fhieutube.com%2F&#038;format=xml" /></head><body><div class="loader loader--center-left"> <img class="loader__img" src="https://hieutube.com/wp-content/themes/hieutube/dist/assets/images/loader.38c12fcb5a5c0a8aa054bf7f4766f8f4.gif" alt="Nyan Cat"/></div><main class="main"><div class="block block--marquee" data-aos="fade"><div class="marquee"><div class="marquee__scroll marquee__scroll--fast"><div class="marquee__content"><p class="">{{ $data.project.title }}</p></div></div></div><div class="marquee"><div class="marquee__scroll marquee__scroll--reverse"><div class="marquee__content"><p class="is-special">{{ $data.JD.title }}</p></div></div></div><div class="marquee"><div class="marquee__scroll marquee__scroll--fast"><div class="marquee__content"><p class="is-special"> {{ $data.Organization.name }} c/o {{ $data.Founder.name }}</p></div></div></div></div><div class="block block--text" data-aos="zoom-in"><div class="text-entry"><p>Coming up: {{ $data.activity.title }}</p></div></div><div class="block block--text" data-aos="zoom-in"><div class="text-entry"><p>Hopefully Covid-19 drama is over soon.. I want to socialize?</p></div></div></main> <script type='text/javascript' src='https://hieutube.com/wp-content/themes/hieutube/dist/runtime.d989a0fdc7f7de2ef305.js?ver=1.0.0'></script> <script type='text/javascript' src='https://hieutube.com/wp-content/themes/hieutube/dist/vendor.28b2f1cdc0bcd148c668.js?ver=1.0.0'></script> <script type='text/javascript' src='https://hieutube.com/wp-content/themes/hieutube/dist/app.92e4a4a89f916da43768.js?ver=1.0.0'></script> <script type='text/javascript' src='https://hieutube.com/wp-includes/js/wp-embed.min.js?ver=5.4.1'></script> </body></html>